services:
  logger:
    build:
      context: ./logger
    container_name: logger
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - logger_instance:/app/instance
volumes:
  logger_instance:
