night:
  after_sunset_minutes: 30
  before_sunrise_minutes: 30
tc_rounding:
  comment: Tableau 4.1 Transport Canada - Arrondi des minutes en décimales
  rules:
  - min: 0
    max: 2
    decimal: 0.0
  - min: 3
    max: 8
    decimal: 0.1
  - min: 9
    max: 14
    decimal: 0.2
  - min: 15
    max: 20
    decimal: 0.3
  - min: 21
    max: 26
    decimal: 0.4
  - min: 27
    max: 32
    decimal: 0.5
  - min: 33
    max: 38
    decimal: 0.6
  - min: 39
    max: 44
    decimal: 0.7
  - min: 45
    max: 50
    decimal: 0.8
  - min: 51
    max: 56
    decimal: 0.9
  - min: 57
    max: 60
    decimal: 0.0
    add_hour: true
