categories:
  - position: 1
    affichage: year
    groupe: date
    colonne_technique: year
    import:
      - year
  - position: 2
    affichage: month
    groupe: date
    colonne_technique: month
    import:
      - month
  - position: 3
    affichage: day
    groupe: date
    colonne_technique: day
    import:
      - day
  - position: 4
    affichage: type
    groupe: aircraft
    colonne_technique: type
    import:
      - type
  - position: 5
    affichage: registration
    groupe: aircraft
    colonne_technique: registration
    import:
      - immat
      - reg
      - registration
  - position: 6
    affichage: pilot in command
    groupe: crew
    colonne_technique: pilot_in_command
    import:
      - pic
  - position: 7
    affichage: copilot
    groupe: crew
    colonne_technique: copilot
    import:
      - copi
  - position: 8
    affichage: departure
    groupe: airports
    colonne_technique: departure
    import:
      - dep
  - position: 9
    affichage: arrival
    groupe: airports
    colonne_technique: arrival
    import:
      - arr
  - position: 10
    affichage: remarks
    groupe: misc
    colonne_technique: remarks
    import:
      - remarks
  - position: 11
    affichage: single engine dual day
    groupe: time
    colonne_technique: single_engine_dual_day
    import:
      - se dual day
  - position: 12
    affichage: single engine pic day
    groupe: time
    colonne_technique: single_engine_pic_day
    import:
      - se pic day
  - position: 13
    affichage: single engine dual night
    groupe: time
    colonne_technique: single_engine_dual_night
    import:
      - se dual night
  - position: 14
    affichage: single engine pic night
    groupe: time
    colonne_technique: single_engine_pic_night
    import:
      - se pic night
